In [6]:
import numpy as np
from __future__ import print_function

## Load the numbers from numbers.txt


In [7]:
loaded_items=np.genfromtxt('numbers.txt', delimiter=',')
print(loaded_items)

[[10. 15. 20. 30.]
 [20. 25. 50. 80.]
 [50. 54. 55. 70.]
 [30. 35. 60. 13.]
 [40. 45. 70. 30.]
 [60. 66. 12. 17.]]


In [11]:
SumOnEachLine=np.sum(loaded_items,axis=1)
print(SumOnEachLine)

[ 75. 175. 229. 138. 185. 155.]


In [12]:
SumAll=np.sum(loaded_items)
print(SumAll)

957.0


In [16]:
count=0
Greater=[loaded_items[loaded_items>30.1]]

for x in np.nditer(Greater):
    count+=1
    
print(count)

13


In [15]:
Greater=[loaded_items[loaded_items>30.1]]
print(Greater)

[array([50., 80., 50., 54., 55., 70., 35., 60., 40., 45., 70., 60., 66.])]


In [17]:
ConcatenateArray= np.concatenate((loaded_items), axis=None)
print(ConcatenateArray)

[10. 15. 20. 30. 20. 25. 50. 80. 50. 54. 55. 70. 30. 35. 60. 13. 40. 45.
 70. 30. 60. 66. 12. 17.]


In [50]:
counter1 = 0
Array2 = np.zeros([6, 4])
for x in np.nditer(loaded_items):
    if ([loaded_items[loaded_items < x]])
        counter += 1
        Array2 = [loaded_items[loaded_items < x]]
    else :continue

print(Array2)

SyntaxError: invalid syntax (<ipython-input-50-056766a24b0c>, line 4)